### ISSUE TITLE
Resources cleanup is missing is case of async exceptions

### ISSUE THREAD

**Issue by Martoon-00** [roman/Haskell-componentm#5]
If a thread during `runComponentM` call receives an asynchronous exception (for instance, during execution of the function which resources were allocated for), then that call just exits without releasing allocated resources.

This indeed happens because `try`/`tryAny` from `exceptions-safe` package are used to catch exceptions, and they fully ignore async exceptions. At the same time, resources cleanup is not part of any `finally`-like construction which would make sure the cleanup always occurs.

What do you think?
If you consider this a true issue, I would be glad to assist in its resolution.

**Comment by roman** [comment]
I believe this is an issue, `runComponentM` should guarantee the release of resources, if this is the case, then let us use `Control.Exception` functions instead. Happy to accept a PR

**Comment by Martoon-00** [comment]
Thanks. I opened a PR, would like to get comments on it :)

**Comment by Martoon-00** [comment]
Resolved in #6
